export const ORDER_STRINGS = {
  ru: {
    title: 'Оформление доставки',
    subtitle: 'Выберите параметры для расчета отправления',
    route: 'Маршрут',
    fromPlaceholder: 'Откуда: начните вводить адрес',
    fromError: 'Заполните поле Откуда',
    toPlaceholder: 'Куда: начните вводить адрес',
    toError: 'Заполните поле Куда',
    addressSuggestions: 'Подсказки адресов',
    packageSize: 'Размер посылки',
    speed: 'Скорость доставки',
    speedLabels: {
      regular: 'Обычная',
      fast: 'Приоритетная'
    },
    calculate: 'Рассчитать',
    resultTitle: 'Расчеты вашего заказа',
    distance: 'Расстояние',
    duration: 'Доставим через',
    rate: 'Тариф',
    total: 'Итого',
    distanceUnit: ' км',
    durationUnit: ' дн.',
    rateUnit: ' ₽/км',
    contacts: 'Контакты',
    namePlaceholder: 'Ваше имя',
    nameError: 'Заполните имя',
    phonePlaceholder: 'Ваш телефон',
    phoneError: 'Заполните телефон',
    extraInfo: 'Дополнительная информация',
    commentPlaceholder: 'Детали доставки и комментарии',
    submit: 'Отправить заявку',
    successSent: 'Заявка отправлена!',
    successNumber: 'Номер отправления – ',
    successSubtitle: 'Мы скоро свяжемся с вами',
    routeCalculationFail: 'Не удалось построить маршрут. Проверьте адреса и выбранные параметры.',
    calculateFirstError: 'Сначала рассчитайте стоимость, чтобы оформить заявку',
    invalidFormError: 'Введите имя и корректный телефон',
    orderSuccessToast: 'Заявка успешно оформлена',
    submissionError: 'Ошибка при отправке заявки',
    geolocationFail: 'Не удалось определить ваше местоположение. Показана карта Москвы.'
  },
  en: {
    title: 'Delivery order',
    subtitle: 'Choose parameters to calculate shipment',
    route: 'Route',
    fromPlaceholder: 'From: start typing address',
    fromError: 'Fill in the From field',
    toPlaceholder: 'To: start typing address',
    toError: 'Fill in the To field',
    addressSuggestions: 'Address suggestions',
    packageSize: 'Package size',
    speed: 'Delivery speed',
    speedLabels: {
      regular: 'Regular',
      fast: 'Priority'
    },
    calculate: 'Calculate',
    resultTitle: 'Your order estimates',
    distance: 'Distance',
    duration: 'Delivery in',
    rate: 'Rate',
    total: 'Total',
    distanceUnit: ' km',
    durationUnit: ' days',
    rateUnit: ' ₽/km',
    contacts: 'Contacts',
    namePlaceholder: 'Your name',
    nameError: 'Enter your name',
    phonePlaceholder: 'Your phone',
    phoneError: 'Enter your phone',
    extraInfo: 'Additional information',
    commentPlaceholder: 'Delivery details and comments',
    submit: 'Submit order',
    successSent: 'Order submitted!',
    successNumber: 'Tracking number – ',
    successSubtitle: 'We will contact you shortly',
    routeCalculationFail: 'Failed to build route. Check addresses and selected parameters.',
    calculateFirstError: 'Calculate cost before submitting an order',
    invalidFormError: 'Enter a name and valid phone',
    orderSuccessToast: 'Order placed successfully',
    submissionError: 'Error submitting order',
    geolocationFail: 'Unable to determine your location. Moscow map shown.'
  }
};
