export const ORDER_STRINGS = {
  title: 'Оформление доставки',
  subtitle: 'Выберите параметры для расчета отправления',
  route: 'Маршрут',
  fromPlaceholder: 'Откуда: начните вводить адрес',
  fromError: 'Заполните поле Откуда',
  toPlaceholder: 'Куда: начните вводить адрес',
  toError: 'Заполните поле Куда',
  packageSize: 'Размер посылки',
  speed: 'Скорость доставки',
  calculate: 'Рассчитать',
  resultTitle: 'Расчеты вашего заказа',
  distance: 'Расстояние',
  duration: 'Доставим через',
  rate: 'Тариф',
  total: 'Итого',
  contacts: 'Контакты',
  namePlaceholder: 'Ваше имя',
  nameError: 'Заполните имя',
  phonePlaceholder: 'Ваш телефон',
  phoneError: 'Заполните телефон',
  extraInfo: 'Дополнительная информация',
  commentPlaceholder: 'Детали доставки и комментарии',
  submit: 'Отправить заявку',
  successSent: 'Заявка отправлена!',
  successNumber: 'Номер отправления – ',
  successSubtitle: 'Мы скоро свяжемся с вами',
  routeCalculationFail: 'Не удалось построить маршрут. Проверьте адреса и выбранные параметры.',
  calculateFirstError: 'Сначала рассчитайте стоимость, чтобы оформить заявку',
  invalidFormError: 'Введите имя и корректный телефон',
  orderSuccessToast: 'Заявка успешно оформлена',
  submissionError: 'Ошибка при отправке заявки',
  geolocationFail: 'Не удалось определить ваше местоположение. Показана карта Москвы.'
};
